### ISSUE TITLE
Comments are stripped from Kotlin code

### ISSUE THREAD

**Issue by vsg24** [angelolloqui/SwiftKotlin#76] opened 2018-06-21 09:05 UTC
<img width="1003" alt="screen shot 2018-06-21 at 1 32 59 pm" src="https://user-images.githubusercontent.com/7500363/41709120-ae4168d2-7557-11e8-8580-92fd52d44f4d.png">

In the project README there's a pic that shows that comments are colored green and are preserved in the Kotlin code but that's not how this tool behaves for me.

And also extra spaces are not preserved.

**Comment by angelolloqui** [comment] 2018-06-21 12:06
Yes, the pic was from a previous version where there was no AST used for the code transaltion. As a result, comments were properly preserved but not anymore. In exchange for that, we have a much more powerful kotlin result.

I am closing the issue as a duplicate of #36

**Closed as completed by angelolloqui** 2018-06-21 12:06 UTC
